[project]
name = "housepricepredictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.128.0",
    "kagglehub>=0.4.2",
    "mlflow>=3.9.0",
    "motor>=3.7.1",
    "smogn>=0.1.2",
]
